gantt
dateFormat X
title Cybercon0 Event Flow (Testnet 0/Rinkeby)

section Flow
Auction                 :         auction, 1543302000, 1543330800 
Talk Applications       :         applications, 1543302000, 1543323600
Talk Accept or Decline  :         verification, 1543302000, 1543330800
Self Decline Talk       :        return, 1543323600, 1543330800
CheckIn, Conference     :         checkin, 1543330800, 1543338000
Distribution            :         distribution, 1543339800, 1543345200 